import {VideoObject} from "../implementations/VideoObject";

export const Videos:VideoObject[] = [
	{
		id: 1,
		title: "TypeScript Course In",
		creator: 1,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 2,
		title: "Pletení",
		creator: 1,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 3,
		title: "Praní",
		creator: 1,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 4,
		title: "Šití",
		creator: 2,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 5,
		title: "Plavání",
		creator: 2,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 6,
		title: "Běh",
		creator: 2,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 7,
		title: "Tanec",
		creator: 3,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 8,
		title: "Šerm",
		creator: 3,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
	{
		id: 9,
		title: "Padání",
		creator: 3,
		video: require("./videos/TypeScript Course In ReactJS - TypeScript.mp4"),
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
		createdAt: "10. 11.2020",
		publishedAt: "12.12.2021",
	},
]